import uuid
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, HTTPException, Query, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from src.rag import KnowledgeBase
from src.crm import CRMClient
from src.agent import SalesAgent

app = FastAPI(
    title="Kayf CRM Chatbot API",
    description="API endpoints to interact with the Kayf Sales Agent and CRM system",
    version="1.0.0"
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global instances of RAG KnowledgeBase and CRM Client
kb = KnowledgeBase()
crm = CRMClient()

# Schemas
class ChatRequest(BaseModel):
    message: str = Field(..., description="The message sent by the user")
    user_id: str = Field("guest", description="Unique user identifier (or 'guest')")
    conversation_id: Optional[str] = Field(None, description="Optional conversation ID. If not provided, a new one is generated.")

class ChatResponse(BaseModel):
    response: str = Field(..., description="The response generated by the sales agent")
    user_id: str = Field(..., description="The user ID associated with this turn")
    conversation_id: str = Field(..., description="The active conversation ID")

class TicketResponse(BaseModel):
    id: str = Field(..., alias="_id")
    user_id: str
    conversation_id: str
    email: Optional[str] = None
    phone: Optional[str] = None
    name: Optional[str] = None
    status: str
    lead_source: str
    created_at: str
    updated_at: str
    products: Dict[str, Any]
    notes: List[str]

    class Config:
        populate_by_name = True

# Helper to get SalesAgent instance
def get_agent() -> SalesAgent:
    return SalesAgent(kb, crm)

@app.get("/api/health", tags=["System"])
def health_check():
    """Check the health status of the API and database connections."""
    if crm.connected and crm.client:
        try:
            crm.client.admin.command("ping")
            db_status = "connected"
        except Exception as e:
            db_status = f"error pinging: {str(e)}"
    else:
        db_status = "offline (in-memory mode)"
    
    return {
        "status": "healthy",
        "database": db_status
    }

@app.post("/api/chat", response_model=ChatResponse, tags=["Chat"])
def chat(request: ChatRequest, agent: SalesAgent = Depends(get_agent)):
    """
    Send a message to the Kayf Sales Agent and get a response.
    If no `conversation_id` is provided, a new unique conversation ID will be generated.
    """
    conv_id = request.conversation_id or str(uuid.uuid4())
    try:
        response_text = agent.generate_response(
            user_input=request.message,
            user_id=request.user_id,
            conversation_id=conv_id
        )
        return ChatResponse(
            response=response_text,
            user_id=request.user_id,
            conversation_id=conv_id
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to process chat message: {str(e)}")

@app.get("/api/tickets", response_model=List[Dict[str, Any]], tags=["CRM Tickets"])
def get_tickets(
    status: Optional[str] = Query(None, description="Filter by ticket status (e.g., hot, warm, cold)"),
    email: Optional[str] = Query(None, description="Filter by user email")
):
    """
    Retrieve all CRM lead tickets. Can be filtered by status or email.
    """
    try:
        tickets = crm.get_all_tickets()
        filtered = []
        for t in tickets:
            # MongoDB ObjectId serialization helper
            if "_id" in t:
                t["_id"] = str(t["_id"])
            
            # Apply status filter
            if status and t.get("status") != status.lower():
                continue
            # Apply email filter
            if email and t.get("email") != email.lower():
                continue
            
            filtered.append(t)
        return filtered
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to retrieve tickets: {str(e)}")

@app.get("/api/tickets/{conversation_id}", response_model=Dict[str, Any], tags=["CRM Tickets"])
def get_ticket(conversation_id: str):
    """
    Retrieve details of a specific CRM ticket by its conversation ID.
    """
    try:
        tickets = crm.get_all_tickets()
        for t in tickets:
            if t.get("conversation_id") == conversation_id:
                if "_id" in t:
                    t["_id"] = str(t["_id"])
                return t
        raise HTTPException(status_code=404, detail=f"Ticket not found for conversation_id: {conversation_id}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to retrieve ticket: {str(e)}")

@app.get("/api/logs", response_model=List[Dict[str, Any]], tags=["Monitoring"])
def get_logs(
    user_id: Optional[str] = Query(None, description="Filter logs by user ID"),
    model: Optional[str] = Query(None, description="Filter logs by LLM model")
):
    """
    Retrieve usage and cost logs for monitoring.
    """
    try:
        logs = crm.get_all_usage_logs()
        filtered = []
        for l in logs:
            if "_id" in l:
                l["_id"] = str(l["_id"])
            if user_id and l.get("user_id") != user_id:
                continue
            if model and l.get("model") != model:
                continue
            filtered.append(l)
        return filtered
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to retrieve logs: {str(e)}")
